<a href="https://colab.research.google.com/github/rltruter/Credit-Risk-Baseline/blob/main/Credit_Risk_Baseline_EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Read in Data

In [1]:
import os

directory_path = '/content/drive/MyDrive/Credit Risk Baseline Data'

# Check if the directory exists
if os.path.exists(directory_path):
    files = os.listdir(directory_path)
    if files:
        print(f"Files in '{directory_path}':")
        for file_name in files:
            print(file_name)
    else:
        print(f"The directory '{directory_path}' is empty.")
else:
    print(f"The directory '{directory_path}' does not exist.")

Files in '/content/drive/MyDrive/Credit Risk Baseline Data':
LCDataDictionary.xlsx
loan.csv
.ipynb_checkpoints

In [2]:
import pandas as pd
import os

directory_path = '/content/drive/MyDrive/Credit Risk Baseline Data'

# Define file paths for the second and third files
excel_file_path = os.path.join(directory_path, 'LCDataDictionary.xlsx')
csv_file_path = os.path.join(directory_path, 'loan.csv')

# Read the Excel file into a DataFrame
try:
    df_data_dictionary = pd.read_excel(excel_file_path)
    print(f"Successfully loaded '{os.path.basename(excel_file_path)}' into df_data_dictionary.")
    print("First 5 rows of df_data_dictionary:")
    display(df_data_dictionary.head())
except FileNotFoundError:
    print(f"Error: The file '{excel_file_path}' was not found.")
except Exception as e:
    print(f"Error loading Excel file: {e}")

Successfully loaded 'LCDataDictionary.xlsx' into df_data_dictionary.
First 5 rows of df_data_dictionary:

            LoanStatNew                                        Description
0        acc_now_delinq  The number of accounts on which the borrower i...
1  acc_open_past_24mths         Number of trades opened in past 24 months.
2            addr_state  The state provided by the borrower in the loan...
3              all_util              Balance to credit limit on all trades
4            annual_inc  The self-reported annual income provided by th...

In [3]:
# Read the CSV file into a DataFrame
try:
    df_loan_data = pd.read_csv(csv_file_path,low_memory = False)
    print(f"\nSuccessfully loaded '{os.path.basename(csv_file_path)}' into df_loan_data.")
    print("First 5 rows of df_loan_data:")
    display(df_loan_data.head())
except FileNotFoundError:
    print(f"Error: The file '{csv_file_path}' was not found.")
except Exception as e:
    print(f"Error loading CSV file: {e}")

Successfully loaded 'loan.csv' into df_loan_data.
First 5 rows of df_loan_data:

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,NaN,2500,2500,2500.0,36 months,13.56,84.92,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,30000,30000,30000.0,60 months,18.94,777.23,D,D2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,5000,5000,5000.0,36 months,17.97,180.69,D,D1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,4000,4000,4000.0,36 months,18.94,146.51,D,D2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,30000,30000,30000.0,60 months,16.14,731.78,C,C4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

Formating of Charts

In [4]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", 200)
sns.set_style("whitegrid")

# Define the Target Variable

In [6]:
bad_statuses = [
    "Charged Off",
    "Default",
    "Late (31-120 days)",
    "Late (16-30 days)"
]

df_loan_data["target_default"] = df_loan_data["loan_status"].isin(bad_statuses).astype(int)
'''
0 Represents a "good" loan (not in the bad_statuses list).
1 Represents a "bad" loan (in the bad_statuses list).
'''

Check Class Imbalance

In [7]:
df_loan_data["target_default"].value_counts(normalize=True)

target_default
0    0.872905
1    0.127095
Name: proportion, dtype: float64

Categorize by Year

In [10]:
df_loan_data["issue_d"] = pd.to_datetime(df_loan_data["issue_d"], format="%b-%Y")
df_loan_data["issue_year"] = df_loan_data["issue_d"].dt.year

Check for coluns with high occurence of missing data

In [11]:
missing = df_loan_data.isnull().mean().sort_values(ascending=False)
missing.head(20)

id                                            1.000000
member_id                                     1.000000
url                                           1.000000
orig_projected_additional_accrued_interest    0.996273
payment_plan_start_date                       0.995305
hardship_end_date                             0.995305
hardship_start_date                           0.995305
hardship_payoff_balance_amount                0.995305
hardship_last_payment_amount                  0.995305
hardship_type                                 0.995305
hardship_amount                               0.995305
hardship_dpd                                  0.995305
hardship_loan_status                          0.995305
hardship_status                               0.995305
deferral_term                                 0.995305
hardship_length                               0.995305
hardship_reason                               0.995305
settlement_status                             0.985378
debt_settlement_flag_date                     0.985378
settlement_percentage                         0.985378
dtype: float64

Flagging High Missing Features

In [12]:
missing[missing > 0.3]

id                                            1.000000
member_id                                     1.000000
url                                           1.000000
orig_projected_additional_accrued_interest    0.996273
payment_plan_start_date                       0.995305
hardship_end_date                             0.995305
hardship_start_date                           0.995305
hardship_payoff_balance_amount                0.995305
hardship_last_payment_amount                  0.995305
hardship_type                                 0.995305
hardship_amount                               0.995305
hardship_dpd                                  0.995305
hardship_loan_status                          0.995305
hardship_status                               0.995305
deferral_term                                 0.995305
hardship_length                               0.995305
hardship_reason                               0.995305
settlement_status                             0.985378
debt_settlement_flag_date                     0.985378
settlement_percentage                         0.985378
settlement_term                               0.985378
settlement_date                               0.985378
settlement_amount                             0.985378
sec_app_mths_since_last_major_derog           0.984101
sec_app_revol_util                            0.953030
revol_bal_joint                               0.952218
sec_app_earliest_cr_line                      0.952217
sec_app_mort_acc                              0.952217
sec_app_open_act_il                           0.952217
sec_app_chargeoff_within_12_mths              0.952217
sec_app_num_rev_accts                         0.952217
sec_app_collections_12_mths_ex_med            0.952217
sec_app_inq_last_6mths                        0.952217
sec_app_open_acc                              0.952217
verification_status_joint                     0.948807
dti_joint                                     0.946606
annual_inc_joint                              0.946604
desc                                          0.944236
mths_since_last_record                        0.841128
mths_since_recent_bc_dlq                      0.770112
mths_since_last_major_derog                   0.743096
mths_since_recent_revol_delinq                0.672504
next_pymnt_d                                  0.576647
mths_since_last_delinq                        0.512460
il_util                                       0.472803
mths_since_rcnt_il                            0.402502
all_util                                      0.383227
open_acc_6m                                   0.383130
inq_last_12m                                  0.383130
total_cu_tl                                   0.383130
total_bal_il                                  0.383130
open_il_24m                                   0.383130
open_act_il                                   0.383130
open_il_12m                                   0.383130
open_rv_24m                                   0.383130
inq_fi                                        0.383130
max_bal_bc                                    0.383130
open_rv_12m                                   0.383130
dtype: float64

# Analyze Default Rates by Risk Drivers